<a href="https://colab.research.google.com/github/Alister44/melbourne-housing-price-prediction/blob/main/housing_price_prediction_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
RANDOM_STATE = 42

In [2]:
FILE_IN = 'https://raw.githubusercontent.com/Alister44/melbourne-housing-price-prediction/refs/heads/main/data/melb_data_raw.csv'
df_original = pd.read_csv(FILE_IN)
df = df_original.copy()

In [3]:
pd.set_option("display.max_columns", None)
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

Analysis of missing values and types

In [7]:
def info_types_missVals():
    return pd.DataFrame({
        "dtype": df.dtypes,
        "missing count": df.isnull().sum(),
        "missing (%)": (df.isna().mean() * 100).round(2)
    }).sort_values("missing (%)", ascending=False)

info_types_missVals()

                 dtype  missing count  missing (%)
BuildingArea   float64           6450        47.50
YearBuilt      float64           5375        39.58
CouncilArea     object           1369        10.08
Car            float64             62         0.46
Suburb          object              0         0.00
Price          float64              0         0.00
Type            object              0         0.00
Rooms            int64              0         0.00
Address         object              0         0.00
Distance       float64              0         0.00
Method          object              0         0.00
Date            object              0         0.00
SellerG         object              0         0.00
Bathroom       float64              0         0.00
Bedroom2       float64              0         0.00
Postcode       float64              0         0.00
Landsize       float64              0         0.00
Lattitude      float64              0         0.00
Longtitude     float64              0         0.00
Regionname      object              0         0.00
Propertycount  float64              0         0.00

In [5]:
df.describe() # descriptive statistics of numeric columns

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [6]:
df.describe(include='all') # descriptive statistics for all columns

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
count,13580,13580,13580.000000,13580,1.358000e+04,13580,13580,13580,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,12211,13580.000000,13580.000000,13580,13580.000000
unique,314,13378,NaN,3,NaN,5,268,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,8,NaN
top,Reservoir,5 Margaret St,NaN,h,NaN,S,Nelson,27/05/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moreland,NaN,NaN,Southern Metropolitan,NaN
freq,359,3,NaN,9449,NaN,9022,1565,473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1163,NaN,NaN,4695,NaN
mean,NaN,NaN,2.937997,NaN,1.075684e+06,NaN,NaN,NaN,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,NaN,-37.809203,144.995216,NaN,7454.417378
std,NaN,NaN,0.955748,NaN,6.393107e+05,NaN,NaN,NaN,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,NaN,0.079260,0.103916,NaN,4378.581772
min,NaN,NaN,1.000000,NaN,8.500000e+04,NaN,NaN,NaN,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,NaN,-38.182550,144.431810,NaN,249.000000
25%,NaN,NaN,2.000000,NaN,6.500000e+05,NaN,NaN,NaN,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,NaN,-37.856822,144.929600,NaN,4380.000000
50%,NaN,NaN,3.000000,NaN,9.030000e+05,NaN,NaN,NaN,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,NaN,-37.802355,145.000100,NaN,6555.000000
75%,NaN,NaN,3.000000,NaN,1.330000e+06,NaN,NaN,NaN,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,NaN,-37.756400,145.058305,NaN,10331.000000
max,NaN,NaN,10.000000,NaN,9.000000e+06,NaN,NaN,NaN,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,NaN,-37.408530,145.526350,NaN,21650.000000

In [8]:
df['Method'].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [14]:
df["Method"].value_counts(normalize=True)*100

Method
S     66.435935
SP    12.540501
PI    11.516937
VB     8.829161
SA     0.677467
Name: proportion, dtype: float64

In [11]:
df.groupby("Method")["Price"].describe()

,count,mean,std,min,25%,50%,75%,max
Method,,,,,,,,
PI,1564.0,1.133242e+06,730999.729516,85000.0,640000.0,932500.0,1450000.0,9000000.0
S,9022.0,1.087327e+06,613785.634739,185000.0,678000.0,925000.0,1330000.0,7650000.0
SA,92.0,1.025772e+06,547952.730240,240000.0,637375.0,872500.0,1283125.0,3225000.0
SP,1703.0,8.998924e+05,509987.899525,190000.0,550000.0,770000.0,1100000.0,5200000.0
VB,1199.0,1.166510e+06,805411.614931,160000.0,580000.0,940000.0,1550000.0,8000000.0

In [12]:
df.groupby("Method")["Date"].agg(["min", "max"])

              min        max
Method
PI      1/07/2017  9/09/2017
S       1/07/2017  9/09/2017
SA      1/07/2017  9/09/2017
SP      1/07/2017  9/09/2017
VB      1/07/2017  9/09/2017